// src/components/Quotd-core/Download/DownloadFrame.tsx
import { forwardRef } from 'react';
import { QCanvas } from '../QCanvas/QCanvas';

interface DownloadFrameProps {
  width?: number;
  height?: number;
}

export const DownloadFrame = forwardRef<HTMLDivElement, DownloadFrameProps>(
  ({ width, height }, ref) => (
    <div
      ref={ref}
      className="fixed -top-[10000px] -left-[10000px] overflow-hidden m-0 p-0"
      style={{ width: width ? `${width}px` : '1080px', height: height ? `${height}px` : '720px' }}
    >
      <QCanvas variant="download" />
    </div>
  )
);

DownloadFrame.displayName = 'DownloadFrame';

// src/components/Quotd-core/DownloadFrame.vue
<template>
  <div
    ref="downloadFrameRef"
    class="fixed -top-[10000px] -left-[10000px] overflow-hidden m-0 p-0"
    :style="{ width: `${width}px`, height: `${height}px` }"
  >
    <QCanvas variant="download" />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import QCanvas from './QCanvas.vue';

interface DownloadFrameProps {
  width?: number;
  height?: number;
}

withDefaults(defineProps<DownloadFrameProps>(), {
  width: 1080,
  height: 720,
});

const downloadFrameRef = ref<HTMLDivElement>();

defineExpose({
  downloadFrameRef,
});
</script>
