// src/components/Quotd-core/QCanvas/QCanvas.tsx
import { forwardRef, useRef } from 'react';
import { useQuoteStore } from '../../../stores/quoteStore';
import { QImage } from '../QImage/QImage';
import { QTypography } from '../QTypography/QTypography';

interface QCanvasProps {
  variant?: 'display' | 'download';
  canvasRef?: React.RefObject<HTMLDivElement>; // Optional ref to be attached
}

export const QCanvas = forwardRef<HTMLDivElement, QCanvasProps>(
  ({ variant = 'display', canvasRef }, ref) => {
    const {
      currentImageIndex,
      currentWordsIndex,
      currentFontIndex,
      currentFontSize,
      isFontLoading,
      outgoingFontIndex,
      isImageLoading,
      outgoingImageIndex,
      handleFontLoaded,
      handleImageLoaded,
    } = useQuoteStore();

    // Use provided ref or create our own
    const internalRef = useRef<HTMLDivElement>(null);
    const actualRef = canvasRef || internalRef;

    return (
      <div
        className={`relative ${variant === 'download' ? '' : 'mt-[30px]'}`}
        ref={ref || actualRef}
      >
        <div
          className="relative mx-auto w-full"
          style={{
            maxWidth: variant === 'display' ? 580 : 1080,
            aspectRatio: '3 / 2',
          }}
        >
          <QImage
            currentImageIndex={currentImageIndex}
            variant={variant}
            outgoingImageIndex={isImageLoading ? outgoingImageIndex : undefined}
            onImageLoaded={handleImageLoaded}
          >
            <QTypography
              variant={variant}
              currentWordsIndex={currentWordsIndex}
              currentFontIndex={currentFontIndex}
              currentFontSize={currentFontSize}
              outgoingFontIndex={isFontLoading ? outgoingFontIndex : undefined}
              onFontLoaded={handleFontLoaded}
            />
          </QImage>
        </div>
      </div>
    );
  }
);

// src/components/Quotd-core/QCanvas.vue
<template>
  <div
    :class="`relative ${variant === 'download' ? '' : 'mt-[30px]'}`"
    :data-testid="isDisplayVariant ? 'quote-canvas-wrapper' : undefined"
  >
    <div
      class="relative mx-auto w-full"
      :style="{
        'max-width': variant === 'display' ? '580px' : '1080px',
        'aspect-ratio': '3 / 2',
      }"
      :data-testid="isDisplayVariant ? 'quote-canvas' : undefined"
    >
      <QImage
        :currentImageIndex="qs.currentImageIndex"
        :variant="variant"
        :outgoingImageIndex="qs.isImageLoading ? qs.outgoingImageIndex : undefined"
        :onImageLoaded="qs.handleImageLoaded"
      >
        <QTypography
          :variant="variant"
          :currentWordsIndex="qs.currentWordsIndex"
          :currentFontIndex="qs.currentFontIndex"
          :currentFontSize="qs.currentFontSize"
          :outgoingFontIndex="qs.isFontLoading ? qs.outgoingFontIndex : undefined"
          :onFontLoaded="qs.handleFontLoaded"
        />
      </QImage>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useQuoteStore } from '../../stores/quoteStore';
import QImage from './QImage.vue';
import QTypography from './QTypography.vue';

interface QCanvasProps {
  variant?: 'display' | 'download';
}

const props = withDefaults(defineProps<QCanvasProps>(), {
  variant: 'display',
});

const qs = useQuoteStore();
const variant = computed(() => props.variant);
const isDisplayVariant = computed(() => props.variant === 'display');
</script>
