// src/components/Quotd-core/QLayout/QLayout.tsx
import { RefObject, useCallback, useRef } from 'react';
import { IconDownload } from '@tabler/icons-react';
import { DownloadFrame } from '../Download/DownloadFrame';
import { handleDownload } from '../Download/handleDownload';
import { QCanvas } from '../QCanvas/QCanvas';
import { QControls } from '../QControls/QControls';

export function QLayout() {
  const downloadFrameRef = useRef<HTMLDivElement | null>(null);

  const downloadQuote = useCallback(() => {
    if (downloadFrameRef.current) {
      handleDownload(downloadFrameRef as RefObject<HTMLDivElement>)();
    }
  }, []);

  return (
    <div className="text-center">
      <QControls />
      <QCanvas />
      <button
        className="mt-5 inline-flex items-center justify-center min-w-[160px] px-4 py-2 bg-primary text-primary-content hover:brightness-110 rounded"
        onClick={downloadQuote}
        type="button"
      >
        <IconDownload size={20} className="mr-2" />
        Download
      </button>
      <DownloadFrame ref={downloadFrameRef} />
    </div>
  );
}

// src/components/Quotd-core/QLayout.vue
<template>
  <div class="text-center" data-testid="quote-layout">
    <QControls />
    <QCanvas />
    <button
      class="mt-5 inline-flex items-center justify-center min-w-[160px] px-4 py-2 bg-primary text-primary-content hover:brightness-110 rounded"
      @click="downloadQuote"
      type="button"
      data-testid="download-quote-button"
    >
      <IconDownload :size="20" class="mr-2" />
      Download
    </button>
    <DownloadFrame ref="downloadFrameRef" />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { IconDownload } from '@tabler/icons-vue';
import DownloadFrame from './DownloadFrame.vue';
import { handleDownload } from './handleDownload';
import QCanvas from './QCanvas.vue';
import QControls from './QControls.vue';

const downloadFrameRef = ref<InstanceType<typeof DownloadFrame>>();

function downloadQuote() {
  if (downloadFrameRef.value?.downloadFrameRef) {
    handleDownload(downloadFrameRef.value.downloadFrameRef)();
  }
}
</script>
