// src/components/Quotd-core/QTypography.tsx
import { createEffect, createMemo, createSignal, onCleanup } from 'solid-js';
import { WordsList } from '../../data/WordsList';
// Import fonts
import '@fontsource/raleway';
import '@fontsource/roboto-slab';
import '@fontsource/inconsolata';
import '@fontsource/exo-2';
import '@fontsource/maiden-orange';
import '@fontsource/lilita-one';
import '@fontsource/covered-by-your-grace';
import '@fontsource/smooch-sans';
import '@fontsource/syne-mono';
import '@fontsource/walter-turncoat';
import '@fontsource/nothing-you-could-do';
import '@fontsource/josefin-slab';
import '@fontsource/architects-daughter';
import '@fontsource/love-ya-like-a-sister';
import '@fontsource/fredericka-the-great';

import { FontDefinitions } from '../../data/FontDefinitions';

// Helper function to load a font and return a promise that resolves when the font is loaded
export const loadFontByIndex = (fontIndex: number): Promise<void> => {
  return new Promise((resolve) => {
    // Add a hidden element with the target font to enable accurate font loading detection
    // Include styling redundancy to ensure it doesn't affect page styling (e.g. increasing page length)
    const hiddenElement = document.createElement('span');
    Object.assign(hiddenElement.style, {
      fontFamily: `"${FontDefinitions[fontIndex].fontName}"`,
      visibility: 'hidden',
      position: 'absolute',
      pointerEvents: 'none',
      fontSize: '0px',
      margin: 0,
      padding: 0,
      boxSizing: 'border-box',
      maxWidth: 0,
      maxHeight: 0,
    });
    hiddenElement.textContent = '\u00A0'; // Non-breaking space
    document.body.appendChild(hiddenElement);

    document.fonts.ready.then(() => {
      const checkFontLoaded = () => {
        if (document.fonts.check(`1em "${FontDefinitions[fontIndex].fontName}"`)) {
          hiddenElement.remove();
          resolve();
          return true;
        }
        return false;
      };
      const isLoadedPreviously = checkFontLoaded();

      // If not loaded
      if (!isLoadedPreviously) {
        document.fonts.load(`1em "${FontDefinitions[fontIndex].fontName}"`);
        for (let i = 0; i < 50; i++) {
          // Check every 100ms for up to 5s
          setTimeout(() => {
            resolve();
          }, 100);
          if (checkFontLoaded()) {
            break;
          }
        }
        // Clean up if font is not loaded in time
        hiddenElement.remove();
      }
    });
  });
};

interface QuoteTextProps {
  variant?: 'display' | 'download';
  currentWordsIndex: number;
  currentFontIndex: number;
  currentFontSize: number;
  outgoingFontIndex?: number; // Optional prop to handle the case when we're still loading a font
  onFontLoaded?: () => void; // Callback when font is loaded
}

export function QTypography(props: QuoteTextProps) {
  // Use outgoingFontIndex if provided (during loading), otherwise use currentFontIndex
  const displayFontIndex = createMemo(() =>
    typeof props.outgoingFontIndex === 'number' ? props.outgoingFontIndex : props.currentFontIndex,
  );
  const fontDefinition = createMemo(() => FontDefinitions[displayFontIndex()]);
  const variant = () => props.variant ?? 'display';
  const isDisplayVariant = () => variant() !== 'download';
  const words = createMemo(() => WordsList[props.currentWordsIndex]);
  let boxRef: HTMLDivElement | undefined;
  const [viewScaleFactor, setViewScaleFactor] = createSignal(1);

  createEffect(() => {
    if (variant() === 'download') {
      setViewScaleFactor(1080 / 580);
      return;
    }

    const updateScale = () => {
      if (variant() === 'display' && boxRef) {
        const scale = boxRef.offsetWidth / 580;
        setViewScaleFactor(scale);
      }
    };

    const resizeObserver = new ResizeObserver(updateScale);
    if (boxRef) {
      resizeObserver.observe(boxRef);
      updateScale();
    }

    onCleanup(() => resizeObserver.disconnect());
  });

  // Effect to handle font loading
  createEffect(() => {
    // Only try to load the font if we need to (when currentFontIndex != previousFontIndex)
    if (props.outgoingFontIndex !== undefined && props.currentFontIndex !== props.outgoingFontIndex) {
      loadFontByIndex(props.currentFontIndex).then(() => {
        props.onFontLoaded?.();
      });
    }
  });

  return (
    <div
      ref={(el) => (boxRef = el)}
      class="quote-typography absolute inset-0 mx-auto flex"
      style={{
        'max-height': isDisplayVariant() ? '400px' : `${(400 / 580) * 1080}px`,
        'max-width': isDisplayVariant() ? '580px' : '1080px',
        padding: `${2 * viewScaleFactor()}em`,
        'align-items': 'center',
        'justify-content': 'center',
      }}
    >
      <div class="flex flex-col items-center">
        <p
          class="text-center"
          style={{
            'max-width': isDisplayVariant() ? '500px' : `${(500 / 580) * 1080}px`,
            width: '80%',
            'font-family': `"${fontDefinition().fontName}", sans-serif`,
            'font-size': `${props.currentFontSize * fontDefinition().sizingFactor * viewScaleFactor()}em`,
            color: 'white',
            'text-shadow': '2px 2px 4px rgba(0,0,0,0.5)',
            'line-height': `${1.4 * fontDefinition().spacingFactor}`,
          }}
          data-testid={isDisplayVariant() ? 'quote-text' : undefined}
        >
          {words().text}
        </p>
        <p
          class="text-center"
          style={{
            'max-width': isDisplayVariant() ? '500px' : `${(500 / 580) * 1080}px`,
            width: '80%',
            'font-family': `"${fontDefinition().fontName}", sans-serif`,
            'font-size': `${props.currentFontSize * fontDefinition().sizingFactor * viewScaleFactor() - 0.6}em`,
            color: 'white',
            'text-shadow': '2px 2px 4px rgba(0,0,0,0.5)',
            'line-height': `${1.4 * fontDefinition().spacingFactor}`,
          }}
          data-testid={isDisplayVariant() ? 'quote-source' : undefined}
        >
          {words().source} {words().translation}
        </p>
      </div>
    </div>
  );
}

export type { QuoteTextProps };

// src/components/Quotd-core/QTypography.vue
<template>
  <div
    ref="boxRef"
    class="quote-typography absolute inset-0 mx-auto flex"
    :style="{
      'max-height': isDisplayVariant ? '400px' : `${(400 / 580) * 1080}px`,
      'max-width': isDisplayVariant ? '580px' : '1080px',
      padding: `${2 * viewScaleFactor}em`,
      'align-items': 'center',
      'justify-content': 'center',
    }"
  >
    <div class="flex flex-col items-center">
      <p
        class="text-center"
        :style="{
          'max-width': isDisplayVariant ? '500px' : `${(500 / 580) * 1080}px`,
          width: '80%',
          'font-family': `'${fontDefinition.fontName}', sans-serif`,
          'font-size': `${currentFontSize * fontDefinition.sizingFactor * viewScaleFactor}em`,
          color: 'white',
          'text-shadow': '2px 2px 4px rgba(0,0,0,0.5)',
          'line-height': `${1.4 * fontDefinition.spacingFactor}`,
        }"
        :data-testid="isDisplayVariant ? 'quote-text' : undefined"
      >
        {{ words.text }}
      </p>
      <p
        class="text-center"
        :style="{
          'max-width': isDisplayVariant ? '500px' : `${(500 / 580) * 1080}px`,
          width: '80%',
          'font-family': `'${fontDefinition.fontName}', sans-serif`,
          'font-size': `${currentFontSize * fontDefinition.sizingFactor * viewScaleFactor - 0.6}em`,
          color: 'white',
          'text-shadow': '2px 2px 4px rgba(0,0,0,0.5)',
          'line-height': `${1.4 * fontDefinition.spacingFactor}`,
        }"
        :data-testid="isDisplayVariant ? 'quote-source' : undefined"
      >
        {{ words.source }} {{ words.translation }}
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch, onMounted, onUnmounted } from 'vue';
import { WordsList } from '../../data/WordsList';
import { FontDefinitions } from '../../data/FontDefinitions';
import { loadFontByIndex } from './utils';

// Import fonts
import '@fontsource/raleway';
import '@fontsource/roboto-slab';
import '@fontsource/inconsolata';
import '@fontsource/exo-2';
import '@fontsource/maiden-orange';
import '@fontsource/lilita-one';
import '@fontsource/covered-by-your-grace';
import '@fontsource/smooch-sans';
import '@fontsource/syne-mono';
import '@fontsource/walter-turncoat';
import '@fontsource/nothing-you-could-do';
import '@fontsource/josefin-slab';
import '@fontsource/architects-daughter';
import '@fontsource/love-ya-like-a-sister';
import '@fontsource/fredericka-the-great';

interface QuoteTextProps {
  variant?: 'display' | 'download';
  currentWordsIndex: number;
  currentFontIndex: number;
  currentFontSize: number;
  outgoingFontIndex?: number;
  onFontLoaded?: () => void;
}

const props = withDefaults(defineProps<QuoteTextProps>(), {
  variant: 'display',
});

const boxRef = ref<HTMLDivElement>();
const viewScaleFactor = ref(1);

const displayFontIndex = computed(() =>
  typeof props.outgoingFontIndex === 'number' ? props.outgoingFontIndex : props.currentFontIndex
);

const fontDefinition = computed(() => FontDefinitions[displayFontIndex.value]);
const isDisplayVariant = computed(() => props.variant !== 'download');
const words = computed(() => WordsList[props.currentWordsIndex]);

// Watch for font loading
watch(
  () => [props.outgoingFontIndex, props.currentFontIndex],
  () => {
    if (props.outgoingFontIndex !== undefined && props.currentFontIndex !== props.outgoingFontIndex) {
      loadFontByIndex(props.currentFontIndex).then(() => {
        props.onFontLoaded?.();
      });
    }
  }
);

// Handle resize observer
onMounted(() => {
  if (props.variant === 'download') {
    viewScaleFactor.value = 1080 / 580;
    return;
  }

  const updateScale = () => {
    if (props.variant === 'display' && boxRef.value) {
      const scale = boxRef.value.offsetWidth / 580;
      viewScaleFactor.value = scale;
    }
  };

  const resizeObserver = new ResizeObserver(updateScale);
  if (boxRef.value) {
    resizeObserver.observe(boxRef.value);
    updateScale();
  }

  onUnmounted(() => {
    resizeObserver.disconnect();
  });
});
</script>
