// src/Layout.vue
<template>
  <div class="min-h-screen flex flex-col">
    <div class="flex-shrink-0">
      <Header />
    </div>
    <main class="flex-1">
      <router-view />
    </main>
    <div class="flex-shrink-0">
      <Footer />
    </div>
  </div>
</template>

<script setup lang="ts">
import Footer from './components/Footer.vue';
import Header from './components/Header.vue';
</script>

// src/Layout.tsx
import { Outlet } from 'react-router-dom';
import { Footer } from './components/Footer/Footer';
import { Header } from './components/Header/Header';

export function Layout() {
  return (
    <div className="min-h-screen flex flex-col">
      <div className="flex-shrink-0">
        <Header />
      </div>
      <main className="flex-1">
        <Outlet />
      </main>
      <div className="flex-shrink-0">
        <Footer />
      </div>
    </div>
  );
}
